Changes in bash script

diff --git a/.github/workflows/reeco_initialize.yml b/.github/workflows/reeco_initialize.yml
--- a/.github/workflows/reeco_initialize.yml
+++ b/.github/workflows/reeco_initialize.yml
@@ -31,7 +31,7 @@ jobs:
         run: |
           git rm -r --ignore-unmatch --cached content
           while IFS= read -r line; do
-            echo "Text read from file: $line"
+              echo "Repository info: $line"
               IN="$line"
               arrIN=(${IN//:/ })
               repo=${arrIN[0]}
@@ -41,19 +41,19 @@ jobs:
               fi
               echo "repo: $repo"
               echo "version: $version"
-              rm -rf "content/_$repo"
+              rm -rf "content/_$repo" && echo "Remove old folder" || echo "Remove old folder failed"
               git clone -n "https://github.com/$repo" "content/_$repo"
-              cd "content/_$repo"
+              cd "content/_$repo" && echo "In folder content/_$repo"
               git ls-tree -r "$version" --full-tree --name-only | grep "\.md" > files.tmp
               while IFS= read -r line; do
                 echo "git checkout $line"
                 git checkout "$version" "$line"
               done < files.tmp
               echo "done < files.tmp"
-              rm files.tmp
-              rm -rf .git
-              cd -
-              echo "committing md files in content/$repo to repo"
+              rm files.tmp && echo "Remove temporary file files.tmp"
+              rm -rf .git && echo "Remove .git folder"
+              cd - && echo "Stepping back to "$(pwd)
+              echo "Committing md files in content/$repo to repo"
               pwd
               cd "content/_$repo"
               pwd
@@ -64,7 +64,7 @@ jobs:
                 git commit -m "updated content in $d"
                 git push
               fi
-              cd ../..
+              cd ../../..
               pwd
           done < repositories.txt
 
