Changes in bash script

diff --git a/.github/workflows/reeco_initialize.yml b/.github/workflows/reeco_initialize.yml
--- a/.github/workflows/reeco_initialize.yml
+++ b/.github/workflows/reeco_initialize.yml
@@ -41,7 +41,7 @@ jobs:
               fi
               echo "repo: $repo"
               echo "version: $version"
-              rm -rf "content/_$repo" #&& echo "Remove old folder" || echo "Remove old folder failed"
+              rm -rf "content/_$repo" && echo "Remove old folder" || echo "Remove old folder failed"
               git clone -n "https://github.com/$repo" "content/_$repo"
               cd "content/_$repo" && echo "In folder content/_$repo"
               git ls-tree -r "$version" --full-tree --name-only | grep "\.md" > files.tmp
@@ -52,16 +52,16 @@ jobs:
               echo "done < files.tmp"
               rm files.tmp && echo "Remove temporary file files.tmp"
               rm -rf .git && echo "Remove .git folder"
-              cd - #&& echo "Stepping back to "$(pwd)
+              cd - && echo "Stepping back to "$(pwd)
               echo "Committing md files in content/$repo to repo"
               pwd
               cd "content/_$repo"
               pwd
               git add *
               changes=0
-              git commit --dry-run && changes=1 || echo "No changes in $d"
-              if [ "$changes" -eq "0" ]; then
-                git commit -m "updated content in $d"
+              git commit --dry-run && changes=1 || echo "No changes in $repo"
+              if [ "$changes" -eq "1" ]; then
+                git commit -m "updated content in $repo"
                 git push
               fi
               cd ../../..
